export interface WebhookConfig {
  id: string
  title: string
  webhookUrl: string
  category: string
  description: string
  expectedFields: string[]
  isActive: boolean
  signingKey?: string // WrapifAI will generate this
  signingKeySet: boolean
}

export const webhookConfigs: WebhookConfig[] = [
  // Assessment & Evaluation Tools
  {
    id: "deaf-individual-assessment",
    title: "Deaf Individual Comprehensive Assessment Tool",
    webhookUrl: "https://vr4deaf.org/api/webhooks/deaf-individual-assessment",
    category: "assessment",
    description: "Receives comprehensive assessment data for deaf individuals",
    expectedFields: [
      "clientId",
      "assessmentResults",
      "communicationPreferences",
      "culturalIdentity",
      "vocationalGoals",
    ],
    isActive: true,
    signingKeySet: false,
  },
  {
    id: "asl-proficiency-evaluator",
    title: "ASL Proficiency & Cultural Identity Evaluator",
    webhookUrl: "https://vr4deaf.org/api/webhooks/asl-proficiency-evaluator",
    category: "assessment",
    description: "Processes ASL proficiency and cultural identity assessment results",
    expectedFields: ["clientId", "aslProficiencyLevel", "culturalIdentityScore", "communicationPreferences"],
    isActive: true,
    signingKeySet: false,
  },
  {
    id: "deaf-cultural-competency",
    title: "Deaf Cultural Competency Assessment",
    webhookUrl: "https://vr4deaf.org/api/webhooks/deaf-cultural-competency",
    category: "assessment",
    description: "Evaluates service provider cultural competency scores",
    expectedFields: ["providerId", "competencyScore", "trainingRecommendations", "certificationStatus"],
    isActive: true,
    signingKeySet: false,
  },
  {
    id: "assistive-technology-evaluator",
    title: "Assistive Technology Evaluator",
    webhookUrl: "https://vr4deaf.org/api/webhooks/assistive-technology-evaluator",
    category: "assessment",
    description: "Processes assistive technology needs assessment results",
    expectedFields: ["clientId", "technologyNeeds", "workplaceRequirements", "costEstimates", "recommendations"],
    isActive: true,
    signingKeySet: false,
  },

  // Career Development & Planning
  {
    id: "deaf-career-explorer",
    title: "Deaf Career Explorer",
    webhookUrl: "https://vr4deaf.org/api/webhooks/deaf-career-explorer",
    category: "career",
    description: "Receives career exploration and job matching results",
    expectedFields: ["clientId", "careerInterests", "skillsAssessment", "jobMatches", "employerRecommendations"],
    isActive: true,
    signingKeySet: false,
  },
  {
    id: "deaf-education-transition",
    title: "Deaf Education Transition Planner",
    webhookUrl: "https://vr4deaf.org/api/webhooks/deaf-education-transition",
    category: "career",
    description: "Processes education-to-employment transition plans",
    expectedFields: ["studentId", "transitionPlan", "skillGaps", "trainingRecommendations", "timelineGoals"],
    isActive: true,
    signingKeySet: false,
  },
  {
    id: "deaf-professional-network",
    title: "Deaf Professional Network & Advocacy Builder",
    webhookUrl: "https://vr4deaf.org/api/webhooks/deaf-professional-network",
    category: "career",
    description: "Handles professional networking and advocacy campaign data",
    expectedFields: ["userId", "networkConnections", "advocacyCampaigns", "professionalGoals", "mentorshipMatches"],
    isActive: true,
    signingKeySet: false,
  },

  // Workplace & Accommodation Tools
  {
    id: "workplace-accommodation-planner",
    title: "Workplace Accommodation Planner",
    webhookUrl: "https://vr4deaf.org/api/webhooks/workplace-accommodation-planner",
    category: "workplace",
    description: "Processes workplace accommodation planning data",
    expectedFields: ["employerId", "accommodationPlan", "costEstimates", "implementationTimeline", "complianceStatus"],
    isActive: true,
    signingKeySet: false,
  },
  {
    id: "accommodation-implementation",
    title: "Accommodation Implementation Guide",
    webhookUrl: "https://vr4deaf.org/api/webhooks/accommodation-implementation",
    category: "workplace",
    description: "Tracks accommodation implementation progress",
    expectedFields: ["employerId", "implementationSteps", "progressStatus", "challenges", "successMetrics"],
    isActive: true,
    signingKeySet: false,
  },
  {
    id: "deaf-employee-integration",
    title: "Deaf Employee Integration Assistant",
    webhookUrl: "https://vr4deaf.org/api/webhooks/deaf-employee-integration",
    category: "workplace",
    description: "Monitors deaf employee integration processes",
    expectedFields: [
      "employeeId",
      "integrationPlan",
      "teamFeedback",
      "accommodationEffectiveness",
      "satisfactionScore",
    ],
    isActive: true,
    signingKeySet: false,
  },
  {
    id: "deaf-workplace-certification",
    title: "Deaf-Inclusive Workplace Certification Tool",
    webhookUrl: "https://vr4deaf.org/api/webhooks/deaf-workplace-certification",
    category: "workplace",
    description: "Processes workplace certification assessments",
    expectedFields: ["employerId", "certificationScore", "complianceAreas", "improvementPlan", "certificationStatus"],
    isActive: true,
    signingKeySet: false,
  },
  {
    id: "roi-calculator",
    title: "ROI Calculator for Accommodating Deaf Employees",
    webhookUrl: "https://vr4deaf.org/api/webhooks/roi-calculator",
    category: "workplace",
    description: "Calculates and tracks accommodation ROI data",
    expectedFields: ["employerId", "accommodationCosts", "productivityGains", "roiPercentage", "timeToBreakeven"],
    isActive: true,
    signingKeySet: false,
  },

  // Financial & Benefits Planning
  {
    id: "benefits-optimization",
    title: "Benefits Optimization Planner",
    webhookUrl: "https://vr4deaf.org/api/webhooks/benefits-optimization",
    category: "financial",
    description: "Processes benefits optimization calculations",
    expectedFields: ["clientId", "currentBenefits", "workIncentives", "optimizationPlan", "projectedIncome"],
    isActive: true,
    signingKeySet: false,
  },
  {
    id: "financial-independence",
    title: "Financial Independence Planner",
    webhookUrl: "https://vr4deaf.org/api/webhooks/financial-independence",
    category: "financial",
    description: "Tracks financial independence planning progress",
    expectedFields: ["clientId", "financialGoals", "savingsStrategy", "investmentPlan", "milestoneProgress"],
    isActive: true,
    signingKeySet: false,
  },
  {
    id: "vr-funding-eligibility",
    title: "VR Funding Eligibility Checker",
    webhookUrl: "https://vr4deaf.org/api/webhooks/vr-funding-eligibility",
    category: "financial",
    description: "Processes VR funding eligibility determinations",
    expectedFields: ["clientId", "eligibilityStatus", "fundingPrograms", "applicationRequirements", "nextSteps"],
    isActive: true,
    signingKeySet: false,
  },
  {
    id: "emergency-financial",
    title: "Emergency Financial Assistance Finder",
    webhookUrl: "https://vr4deaf.org/api/webhooks/emergency-financial",
    category: "financial",
    description: "Handles emergency financial assistance requests",
    expectedFields: ["clientId", "emergencyType", "assistancePrograms", "applicationStatus", "urgencyLevel"],
    isActive: true,
    signingKeySet: false,
  },

  // Service Coordination & Resources
  {
    id: "vr-counselor-matchmaker",
    title: "Deaf Client VR Counselor Matchmaker",
    webhookUrl: "https://vr4deaf.org/api/webhooks/vr-counselor-matchmaker",
    category: "services",
    description: "Processes VR counselor matching results",
    expectedFields: [
      "clientId",
      "counselorMatches",
      "matchingCriteria",
      "communicationPreferences",
      "appointmentScheduling",
    ],
    isActive: true,
    signingKeySet: false,
  },
  {
    id: "interpreter-scheduling",
    title: "Sign Language Interpreter Scheduling Assistant",
    webhookUrl: "https://vr4deaf.org/api/webhooks/interpreter-scheduling",
    category: "services",
    description: "Manages interpreter scheduling and coordination",
    expectedFields: ["requestId", "interpreterAssignment", "serviceDetails", "schedulingStatus", "qualityRating"],
    isActive: true,
    signingKeySet: false,
  },
  {
    id: "community-resource-finder",
    title: "Deaf Community Resource Finder",
    webhookUrl: "https://vr4deaf.org/api/webhooks/community-resource-finder",
    category: "services",
    description: "Tracks community resource searches and referrals",
    expectedFields: ["clientId", "resourceType", "locationData", "resourceMatches", "referralStatus"],
    isActive: true,
    signingKeySet: false,
  },
  {
    id: "service-quality-tracker",
    title: "Service Quality Tracker",
    webhookUrl: "https://vr4deaf.org/api/webhooks/service-quality-tracker",
    category: "services",
    description: "Monitors service quality metrics and outcomes",
    expectedFields: ["serviceId", "qualityMetrics", "clientFeedback", "outcomeData", "improvementRecommendations"],
    isActive: true,
    signingKeySet: false,
  },

  // Compliance & Accessibility
  {
    id: "ada-compliance-checker",
    title: "ADA Compliance Checker",
    webhookUrl: "https://vr4deaf.org/api/webhooks/ada-compliance-checker",
    category: "compliance",
    description: "Processes ADA compliance assessment results",
    expectedFields: ["organizationId", "complianceScore", "violationAreas", "remediationPlan", "complianceStatus"],
    isActive: true,
    signingKeySet: false,
  },
  {
    id: "accessibility-evaluator",
    title: "Deaf Community Accessibility Evaluator",
    webhookUrl: "https://vr4deaf.org/api/webhooks/accessibility-evaluator",
    category: "compliance",
    description: "Evaluates community accessibility for deaf individuals",
    expectedFields: [
      "locationId",
      "accessibilityScore",
      "barrierIdentification",
      "improvementSuggestions",
      "priorityLevel",
    ],
    isActive: true,
    signingKeySet: false,
  },
]
