const express = require("express")
const bodyParser = require("body-parser")
const cors = require("cors")

const app = express()
const port = process.env.PORT || 5000

app.use(cors())
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))

// Route imports
const userRoutes = require("./routes/user.routes")
const authRoutes = require("./routes/auth.routes")
const productRoutes = require("./routes/product.routes")
const orderRoutes = require("./routes/order.routes")
const categoryRoutes = require("./routes/category.routes")
const reviewRoutes = require("./routes/review.routes")
const paymentRoutes = require("./routes/payment.routes")
const shippingRoutes = require("./routes/shipping.routes")
const discountRoutes = require("./routes/discount.routes")
const cartRoutes = require("./routes/cart.routes")
const addressRoutes = require("./routes/address.routes")
const newsletterRoutes = require("./routes/newsletter.routes")
const contactRoutes = require("./routes/contact.routes")
const blogRoutes = require("./routes/blog.routes")
const faqRoutes = require("./routes/faq.routes")
const pageRoutes = require("./routes/page.routes")
const settingRoutes = require("./routes/setting.routes")
const referralRoutes = require("./routes/referral.routes")

// Route mounts
app.use("/api/users", userRoutes)
app.use("/api/auth", authRoutes)
app.use("/api/products", productRoutes)
app.use("/api/orders", orderRoutes)
app.use("/api/categories", categoryRoutes)
app.use("/api/reviews", reviewRoutes)
app.use("/api/payments", paymentRoutes)
app.use("/api/shipping", shippingRoutes)
app.use("/api/discounts", discountRoutes)
app.use("/api/cart", cartRoutes)
app.use("/api/address", addressRoutes)
app.use("/api/newsletter", newsletterRoutes)
app.use("/api/contact", contactRoutes)
app.use("/api/blogs", blogRoutes)
app.use("/api/faqs", faqRoutes)
app.use("/api/pages", pageRoutes)
app.use("/api/settings", settingRoutes)
app.use("/api/referrals", referralRoutes)

app.listen(port, () => {
  console.log(`Server is running on port: ${port}`)
})
